name: Python3 tox runner
description: Runs tox py3 targets
inputs:
  tox_target:
    description: "The tox target to run"
    required: true
  py_version:
    description: "The python version to use"
    required: false
    default: '3'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-wxgtk4.0
        sudo python${{ inputs.py_version }} -mpip install tox
    - name: Run tox
      shell: bash
      run: |
        git fetch origin $GITHUB_BASE_REF || true
        tox -e ${{ inputs.tox_target }}
